apiVersion: v1                    
kind: Namespace
metadata:
  name: rhacs-deploy                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: install-rhacs-central-policy
  namespace: rhacs-deploy
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - install-rhacs-central-policy
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-clustership-acspolicy-gitops-acm-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-clustership-acspolicy-gitops-acm
  namespace: ggithubcom-clustership-acspolicy-gitops-acm-ns
spec:
  type: Git
  pathname: 'https://github.com/clustership/acspolicy-gitops-acm.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: centraldeploypolicy
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: install-rhacs-central-policy
  name: install-rhacs-central-policy-subscription-1
  namespace: rhacs-deploy
spec:
  channel: ggithubcom-clustership-acspolicy-gitops-acm-ns/ggithubcom-clustership-acspolicy-gitops-acm
  placement:
    placementRef:
      kind: PlacementRule
      name: install-rhacs-central-policy-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: install-rhacs-central-policy
  name: install-rhacs-central-policy-placement-1
  namespace: rhacs-deploy
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
